# Generated by Django 6.0 on 2026-01-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='questions',
            field=models.ManyToManyField(related_name='concepts', to='dashboard.question'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='dashboard.tag'),
        ),
    ]
