# Generated by Django 6.0 on 2026-01-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_concept_questions_alter_concept_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='defaultQuestions',
            field=models.ManyToManyField(related_name='boards', to='dashboard.question'),
        ),
    ]
