# Generated by Django 6.0 on 2025-12-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='concept',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dashboard.concept'),
        ),
    ]
