# Generated by Django 6.0 on 2025-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tag_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='concept',
        ),
        migrations.AddField(
            model_name='concept',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='dashboard.tag'),
        ),
    ]
