# Generated by Django 6.0 on 2025-12-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='unknown',
            field=models.BooleanField(default=True),
        ),
    ]
