# Generated by Django 6.0 on 2025-12-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_board_user_alter_concept_board'),
        ('user_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.board'),
        ),
    ]
