# Generated by Django 6.0 on 2025-12-23 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0002_alter_log_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
