# Generated by Django 6.0 on 2025-12-24 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0004_alter_log_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
