# Generated by Django 6.0 on 2025-12-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0005_alter_log_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
