# Generated by Django 6.0 on 2025-12-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0006_alter_log_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
