# Generated by Django 6.0 on 2026-01-13 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_alter_concept_questions_alter_concept_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correctAnswers', models.IntegerField(default=0)),
                ('incorrectAnswers', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.board')),
                ('concepts', models.ManyToManyField(blank=True, related_name='sessions', to='dashboard.concept')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('isExclusive', models.BooleanField(default=False)),
                ('numQuestions', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionSettings', to='dashboard.board')),
                ('questionTypes', models.ManyToManyField(related_name='sessionSettings', to='dashboard.question')),
                ('tags', models.ManyToManyField(blank=True, related_name='sessions', to='dashboard.tag')),
            ],
        ),
    ]
