# Generated by Django 6.0 on 2026-01-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_concept_questions_alter_concept_tags'),
        ('study_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsettings',
            name='questionType',
            field=models.ForeignKey(default='answer', on_delete=django.db.models.deletion.CASCADE, related_name='sessionSettings', to='dashboard.question'),
        ),
    ]
