# Generated by Django 6.0 on 2026-01-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_concept_questions_alter_concept_tags'),
        ('study_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='questionTypes',
            field=models.ManyToManyField(related_name='sessions', to='dashboard.question'),
        ),
    ]
