# Generated by Django 6.0 on 2026-01-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0002_session_questiontypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='isExclusive',
            field=models.BooleanField(default=False),
        ),
    ]
