# Generated by Django 6.0 on 2025-12-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0002_alter_session_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='start',
            new_name='dateAdded',
        ),
    ]
