# Generated by Django 6.0 on 2025-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0003_rename_start_session_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='correctAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='incorrectAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='numQuestions',
            field=models.IntegerField(default=0),
        ),
    ]
