# Generated by Django 6.0 on 2025-12-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_concept_unknown'),
        ('study_session', '0004_session_correctanswers_session_incorrectanswers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='dashboard.tag'),
        ),
        migrations.AlterField(
            model_name='session',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='dashboard.concept'),
        ),
    ]
