# Generated by Django 6.0 on 2025-12-30 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_concept_unknown'),
        ('study_session', '0005_session_tags_alter_session_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='numQuestions',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tags',
        ),
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('numQuestions', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionSettings', to='dashboard.board')),
                ('tags', models.ManyToManyField(blank=True, related_name='sessions', to='dashboard.tag')),
            ],
        ),
    ]
