# Generated by Django 6.0 on 2025-12-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_session', '0006_remove_session_numquestions_remove_session_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsettings',
            name='isExclusive',
            field=models.BooleanField(default=False),
        ),
    ]
